/**
 * Anonymous analytics + lead capture (framework-agnostic, D1-backed).
 *
 * PRIVACY IS A FEATURE here:
 *   - No cookies, no persistent identifiers: the session id is generated by
 *     the viewer with crypto.randomUUID(), lives in memory only and dies with
 *     the tab. Two visits by the same person are two unrelated sessions.
 *   - IP addresses and user agents are NEVER stored — the entry points pass
 *     the IP to the rate limiter only, this module never sees it.
 *   - Event payloads are tiny (<=500 chars JSON) and validated against a fixed
 *     type allowlist; free-text only exists where the visitor typed it
 *     deliberately (concierge questions, lead form).
 *
 * Fail-soft contract: analytics must NEVER break the viewer. Without a bound
 * D1 database (`ANALYTICS_DB`), valid batches are answered 202 and dropped.
 * A D1 insert error on /events also yields 202 (logged) — losing a beacon is
 * better than surfacing an error in the tour.
 *
 * The report endpoint is read-only and guarded by a per-property secret token
 * (constant-time compare, uniform 404 on ANY mismatch so it never reveals
 * whether a property exists).
 */
import { ValidationError } from './validation.js';
import { renderReportHtml, renderReportNotFoundHtml } from './report.js';
import type { ReportData, ReportLeadRow } from './report.js';
import type { RateLimitResult } from './ratelimit.js';

// ---------------------------------------------------------------------------
// Structural D1 slice (same pattern as KvLike in ratelimit.ts): declared
// locally so the non-Workers entry points compile without @cloudflare/
// workers-types at their call sites and the module stays unit-testable.
// ---------------------------------------------------------------------------

export interface D1StatementLike {
  bind(...values: unknown[]): D1StatementLike;
  run(): Promise<unknown>;
  all(): Promise<{ results: Record<string, unknown>[] }>;
  first(): Promise<Record<string, unknown> | null>;
}

export interface D1Like {
  prepare(query: string): D1StatementLike;
  batch(statements: D1StatementLike[]): Promise<unknown>;
}

/** A normalized result the entry points translate into their native response. */
export interface AnalyticsResult {
  status: number;
  body: Record<string, unknown>;
  retryAfterSeconds?: number;
}

/**
 * Optional global daily flood cap (see KvDailyBudget in ratelimit.ts). It is
 * consumed AFTER validation and the database check, so garbage requests and
 * unprovisioned deployments never burn budget. When omitted (dev server,
 * Vercel, no KV), no cap is enforced.
 */
export type DailyBudget = { consume(): Promise<RateLimitResult> };

// ---------------------------------------------------------------------------
// Validation caps
// ---------------------------------------------------------------------------

const PROPERTY_ID_RE = /^[a-z0-9-]{1,64}$/; // same shape as the concierge/staging id
const SESSION_ID_RE = /^[a-f0-9-]{8,64}$/; // crypto.randomUUID() and friends
const MAX_EVENTS_PER_REQUEST = 20;
const MAX_DATA_CHARS = 500;
const MAX_TOKEN_CHARS = 256;

const MAX_LEAD_NAME_CHARS = 120;
const MAX_LEAD_CONTACT_CHARS = 200;
const MAX_LEAD_MESSAGE_CHARS = 2000;
const MAX_LEAD_INTEREST_CHARS = 100;

/** The only event types the API accepts — anything else is a 400. */
export const EVENT_TYPES: ReadonlySet<string> = new Set([
  'open',
  'heartbeat',
  'tour_start',
  'tour_complete',
  'aerial',
  'annotation',
  'staging',
  'share',
  'inquiry_click',
  'concierge_question',
  'survey',
  'cta_click',
]);

function isObject(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/** Constant-time token comparison (no early exit on the first differing byte). */
export function tokensMatch(expected: string, provided: string): boolean {
  const enc = new TextEncoder();
  const a = enc.encode(expected);
  const b = enc.encode(provided);
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a[i] ^ b[i];
  return diff === 0;
}

// ---------------------------------------------------------------------------
// POST /events
// ---------------------------------------------------------------------------

interface EventsRequest {
  propertyId: string;
  sessionId: string;
  events: { type: string; data: string | null }[];
}

/** Validate an /events batch. Throws ValidationError (=> 400) on any violation. */
export function validateEventsRequest(body: unknown): EventsRequest {
  if (!isObject(body)) {
    throw new ValidationError('Request body must be a JSON object.');
  }
  const propertyId = body['propertyId'];
  if (typeof propertyId !== 'string' || !PROPERTY_ID_RE.test(propertyId)) {
    throw new ValidationError('Field "propertyId" must match ^[a-z0-9-]{1,64}$.');
  }
  const sessionId = body['sessionId'];
  if (typeof sessionId !== 'string' || !SESSION_ID_RE.test(sessionId)) {
    throw new ValidationError('Field "sessionId" must match ^[a-f0-9-]{8,64}$.');
  }
  const rawEvents = body['events'];
  if (!Array.isArray(rawEvents) || rawEvents.length === 0) {
    throw new ValidationError('Field "events" must be a non-empty array.');
  }
  if (rawEvents.length > MAX_EVENTS_PER_REQUEST) {
    throw new ValidationError(`Too many events (max ${MAX_EVENTS_PER_REQUEST}).`);
  }
  const events = rawEvents.map((raw, i) => {
    if (!isObject(raw)) {
      throw new ValidationError(`events[${i}] must be an object.`);
    }
    const type = raw['type'];
    if (typeof type !== 'string' || !EVENT_TYPES.has(type)) {
      throw new ValidationError(`events[${i}].type is not an allowed event type.`);
    }
    let data: string | null = null;
    if (raw['data'] !== undefined && raw['data'] !== null) {
      const serialized = JSON.stringify(raw['data']);
      if (serialized === undefined || serialized.length > MAX_DATA_CHARS) {
        throw new ValidationError(`events[${i}].data exceeds ${MAX_DATA_CHARS} JSON characters.`);
      }
      data = serialized;
    }
    return { type, data };
  });
  return { propertyId, sessionId, events };
}

/**
 * Store a validated event batch. Timestamps are SERVER time — the client
 * cannot backdate or forge them, and no client clock data is retained.
 * Without a database the batch is accepted (202) and dropped silently.
 */
export async function handleEvents(
  rawBody: unknown,
  db: D1Like | undefined,
  dailyBudget?: DailyBudget,
): Promise<AnalyticsResult> {
  let request: EventsRequest;
  try {
    request = validateEventsRequest(rawBody);
  } catch (err) {
    if (err instanceof ValidationError) {
      return { status: 400, body: { error: err.message } };
    }
    return { status: 400, body: { error: 'Invalid request.' } };
  }

  if (!db) {
    // No ANALYTICS_DB binding: accept and drop. The viewer must never break
    // because analytics is not provisioned.
    return { status: 202, body: { ok: true } };
  }

  // Global daily flood cap: past the cap the batch is accepted (202) and
  // DROPPED silently — same fail-soft contract as everything else here.
  if (dailyBudget) {
    const budget = await dailyBudget.consume();
    if (!budget.allowed) {
      return { status: 202, body: { ok: true } };
    }
  }

  const now = Date.now();
  try {
    const insert = db.prepare(
      'INSERT INTO events (property_id, session_id, ts, type, data) VALUES (?1, ?2, ?3, ?4, ?5)',
    );
    await db.batch(
      request.events.map((e) =>
        insert.bind(request.propertyId, request.sessionId, now, e.type, e.data),
      ),
    );
  } catch (err) {
    // Fail soft: losing a beacon is better than surfacing an error mid-tour.
    console.warn('[analytics] event insert failed (dropped):', String(err));
  }
  return { status: 202, body: { ok: true } };
}

// ---------------------------------------------------------------------------
// POST /lead
// ---------------------------------------------------------------------------

interface LeadRequest {
  propertyId: string;
  name: string;
  contact: string;
  message: string | null;
  interest: string | null;
}

/** Validate a /lead body. Throws ValidationError (=> 400) on any violation. */
export function validateLeadRequest(body: unknown): LeadRequest {
  if (!isObject(body)) {
    throw new ValidationError('Request body must be a JSON object.');
  }
  const propertyId = body['propertyId'];
  if (typeof propertyId !== 'string' || !PROPERTY_ID_RE.test(propertyId)) {
    throw new ValidationError('Field "propertyId" must match ^[a-z0-9-]{1,64}$.');
  }
  // GDPR: consent must be the LITERAL boolean true — no truthy coercion.
  if (body['consent'] !== true) {
    throw new ValidationError('Field "consent" must be true.');
  }
  const name = typeof body['name'] === 'string' ? body['name'].trim() : '';
  if (name.length === 0 || name.length > MAX_LEAD_NAME_CHARS) {
    throw new ValidationError(`Field "name" must be 1–${MAX_LEAD_NAME_CHARS} characters.`);
  }
  const contact = typeof body['contact'] === 'string' ? body['contact'].trim() : '';
  if (contact.length === 0 || contact.length > MAX_LEAD_CONTACT_CHARS) {
    throw new ValidationError(`Field "contact" must be 1–${MAX_LEAD_CONTACT_CHARS} characters.`);
  }
  let message: string | null = null;
  if (body['message'] !== undefined && body['message'] !== null) {
    if (typeof body['message'] !== 'string' || body['message'].length > MAX_LEAD_MESSAGE_CHARS) {
      throw new ValidationError(`Field "message" must be a string up to ${MAX_LEAD_MESSAGE_CHARS} characters.`);
    }
    message = body['message'].trim() || null;
  }
  let interest: string | null = null;
  if (body['interest'] !== undefined && body['interest'] !== null) {
    if (typeof body['interest'] !== 'string' || body['interest'].length > MAX_LEAD_INTEREST_CHARS) {
      throw new ValidationError(`Field "interest" must be a string up to ${MAX_LEAD_INTEREST_CHARS} characters.`);
    }
    interest = body['interest'].trim() || null;
  }
  return { propertyId, name, contact, message, interest };
}

/**
 * Store a lead. Unlike /events, a storage failure IS surfaced (500) — a lead
 * is a customer inquiry, silently dropping it would be worse than an error
 * the client can retry on. Without a database: 202 and drop.
 */
export async function handleLead(
  rawBody: unknown,
  db: D1Like | undefined,
  dailyBudget?: DailyBudget,
): Promise<AnalyticsResult> {
  let request: LeadRequest;
  try {
    request = validateLeadRequest(rawBody);
  } catch (err) {
    if (err instanceof ValidationError) {
      return { status: 400, body: { error: err.message } };
    }
    return { status: 400, body: { error: 'Invalid request.' } };
  }

  if (!db) {
    return { status: 202, body: { ok: true } };
  }

  // Global daily flood cap. A lead is a customer inquiry, so — unlike /events —
  // hitting the cap IS surfaced (429 + Retry-After) instead of dropped silently;
  // the viewer's form shows a friendly retry message on 429.
  if (dailyBudget) {
    const budget = await dailyBudget.consume();
    if (!budget.allowed) {
      return {
        status: 429,
        body: { error: 'The daily inquiry limit is reached. Please try again tomorrow.' },
        retryAfterSeconds: budget.retryAfterSeconds,
      };
    }
  }

  try {
    await db
      .prepare(
        'INSERT INTO leads (property_id, ts, name, contact, message, interest, consent) VALUES (?1, ?2, ?3, ?4, ?5, ?6, 1)',
      )
      .bind(request.propertyId, Date.now(), request.name, request.contact, request.message, request.interest)
      .run();
  } catch (err) {
    console.warn('[analytics] lead insert failed:', String(err));
    return { status: 500, body: { error: 'Could not store the inquiry. Please try again.' } };
  }
  return { status: 202, body: { ok: true } };
}

// ---------------------------------------------------------------------------
// GET /report/{propertyId}?token=...
// ---------------------------------------------------------------------------

export interface ReportResult {
  status: number;
  /** Self-contained HTML document (text/html; charset=utf-8). */
  html: string;
}

/**
 * Render the owner report. ANY failure to authorize — unknown property, no
 * token configured, wrong token, no database — returns the SAME 404 page so
 * the endpoint never reveals whether a property exists.
 */
export async function handleReport(
  propertyId: string,
  token: string,
  db: D1Like | undefined,
): Promise<ReportResult> {
  const notFound: ReportResult = { status: 404, html: renderReportNotFoundHtml() };

  if (!db) return notFound;
  if (!PROPERTY_ID_RE.test(propertyId)) return notFound;
  if (token.length === 0 || token.length > MAX_TOKEN_CHARS) return notFound;

  let property: Record<string, unknown> | null;
  try {
    property = await db
      .prepare('SELECT report_token, label FROM properties WHERE property_id = ?1')
      .bind(propertyId)
      .first();
  } catch (err) {
    console.warn('[analytics] report property lookup failed:', String(err));
    return notFound;
  }

  const expected = typeof property?.['report_token'] === 'string' ? (property['report_token'] as string) : null;
  // Burn a compare even when the row/token is missing so the miss path costs
  // the same as a near-miss; the uniform 404 hides existence either way.
  const provided = token;
  const matches = expected !== null && expected.length > 0
    ? tokensMatch(expected, provided)
    : (tokensMatch(provided, provided), false);
  if (!matches) return notFound;

  try {
    const data = await collectReportData(db, propertyId, typeof property?.['label'] === 'string' ? (property['label'] as string) : null);
    return { status: 200, html: renderReportHtml(data) };
  } catch (err) {
    console.warn('[analytics] report aggregation failed:', String(err));
    return { status: 500, html: renderReportNotFoundHtml() };
  }
}

/** Run all report aggregations in SQL and shape them for the renderer. */
async function collectReportData(
  db: D1Like,
  propertyId: string,
  label: string | null,
): Promise<ReportData> {
  const kpis = await db
    .prepare(
      `SELECT
         COUNT(CASE WHEN type = 'open' THEN 1 END)          AS opens,
         COUNT(CASE WHEN type = 'tour_start' THEN 1 END)    AS tour_starts,
         COUNT(CASE WHEN type = 'tour_complete' THEN 1 END) AS tour_completes,
         COUNT(CASE WHEN type = 'staging' THEN 1 END)       AS stagings,
         COUNT(CASE WHEN type = 'share' THEN 1 END)         AS shares,
         COUNT(CASE WHEN type = 'cta_click' THEN 1 END)     AS cta_clicks
       FROM events WHERE property_id = ?1`,
    )
    .bind(propertyId)
    .first();

  // Dwell time per session from the heartbeat payloads: each heartbeat carries
  // the session's accumulated VISIBLE seconds (the viewer's clock stops while
  // the tab is hidden), so the highest value per session is that session's
  // dwell — unlike server-timestamp spans, hidden-tab gaps don't count. Each
  // session is capped at 30 min so one tab left open cannot inflate the
  // average; sessions without heartbeats are ignored.
  const dwell = await db
    .prepare(
      `SELECT AVG(dur_s) AS avg_dwell_s FROM (
         SELECT MIN(MAX(json_extract(data, '$.seconds')), 1800) AS dur_s
         FROM events
         WHERE property_id = ?1 AND type = 'heartbeat'
           AND typeof(json_extract(data, '$.seconds')) IN ('integer', 'real')
         GROUP BY session_id
       )`,
    )
    .bind(propertyId)
    .first();

  const annotations = await db
    .prepare(
      `SELECT data, COUNT(*) AS n FROM events
       WHERE property_id = ?1 AND type = 'annotation' AND data IS NOT NULL
       GROUP BY data ORDER BY n DESC LIMIT 8`,
    )
    .bind(propertyId)
    .all();

  const survey = await db
    .prepare(
      `SELECT data, COUNT(*) AS n FROM events
       WHERE property_id = ?1 AND type = 'survey'
       GROUP BY data`,
    )
    .bind(propertyId)
    .all();

  const questions = await db
    .prepare(
      `SELECT ts, data FROM events
       WHERE property_id = ?1 AND type = 'concierge_question' AND data IS NOT NULL
       ORDER BY ts DESC LIMIT 100`,
    )
    .bind(propertyId)
    .all();

  const leads = await db
    .prepare(
      `SELECT ts, name, contact, interest FROM leads
       WHERE property_id = ?1 ORDER BY ts DESC LIMIT 200`,
    )
    .bind(propertyId)
    .all();

  const num = (row: Record<string, unknown> | null, key: string): number => {
    const v = row?.[key];
    return typeof v === 'number' && Number.isFinite(v) ? v : 0;
  };

  // 1-5 helpfulness scale ("Wie hilfreich war dieser Rundgang?")
  const surveyBuckets = [0, 0, 0, 0, 0];
  for (const row of survey.results) {
    const rating = extractSurveyRating(row['data']);
    const n = typeof row['n'] === 'number' ? row['n'] : 0;
    if (rating !== null && rating >= 1 && rating <= 5) surveyBuckets[rating - 1] += n;
  }

  const avgDwellRaw = dwell?.['avg_dwell_s'];

  return {
    propertyId,
    label,
    generatedAt: Date.now(),
    opens: num(kpis, 'opens'),
    avgDwellMs: typeof avgDwellRaw === 'number' && Number.isFinite(avgDwellRaw) ? avgDwellRaw * 1000 : null,
    tourStarts: num(kpis, 'tour_starts'),
    tourCompletes: num(kpis, 'tour_completes'),
    stagings: num(kpis, 'stagings'),
    shares: num(kpis, 'shares'),
    ctaClicks: num(kpis, 'cta_clicks'),
    annotations: annotations.results.map((row) => ({
      label: extractLabel(row['data']),
      count: typeof row['n'] === 'number' ? row['n'] : 0,
    })),
    survey: surveyBuckets,
    questions: questions.results
      .map((row) => ({
        ts: typeof row['ts'] === 'number' ? row['ts'] : 0,
        text: extractQuestion(row['data']),
      }))
      .filter((q) => q.text.length > 0),
    leads: leads.results.map((row): ReportLeadRow => ({
      ts: typeof row['ts'] === 'number' ? row['ts'] : 0,
      name: typeof row['name'] === 'string' ? row['name'] : '',
      contact: typeof row['contact'] === 'string' ? row['contact'] : '',
      interest: typeof row['interest'] === 'string' ? row['interest'] : null,
    })),
  };
}

/** Parse `{ "rating": 1..5 }` (canonical), a bare number, or numeric string. */
function extractSurveyRating(data: unknown): number | null {
  if (typeof data !== 'string') return null;
  try {
    const parsed: unknown = JSON.parse(data);
    const candidate = isObject(parsed)
      ? (parsed['rating'] ?? parsed['value'])
      : parsed;
    const n = typeof candidate === 'number' ? candidate : Number.parseInt(String(candidate), 10);
    // The viewer's survey card is a 1-5 helpfulness scale (survey.ts) and the
    // report buckets/renderer model 1-5 — this parser capping at 4 silently
    // dropped every TOP rating from the owner report.
    return Number.isInteger(n) && n >= 1 && n <= 5 ? n : null;
  } catch {
    return null;
  }
}

/** Best-effort label from an annotation payload: {label}/{id}/plain string. */
function extractLabel(data: unknown): string {
  if (typeof data !== 'string') return '';
  try {
    const parsed: unknown = JSON.parse(data);
    if (typeof parsed === 'string') return parsed;
    if (isObject(parsed)) {
      const label = parsed['label'] ?? parsed['id'];
      if (typeof label === 'string') return label;
    }
  } catch {
    /* fall through to raw */
  }
  return data;
}

/** Best-effort question text: {q}/{question}/{text}/plain string. */
function extractQuestion(data: unknown): string {
  if (typeof data !== 'string') return '';
  try {
    const parsed: unknown = JSON.parse(data);
    if (typeof parsed === 'string') return parsed.trim();
    if (isObject(parsed)) {
      const q = parsed['q'] ?? parsed['question'] ?? parsed['text'];
      if (typeof q === 'string') return q.trim();
    }
  } catch {
    /* fall through */
  }
  return '';
}
